application: hungrybear-comics
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_dir: static
  
- url: /tasks/.*
  script: tasks.py
  login: admin
  
- url: .*
  script: main.py
  